// <auto-generated />
using CarwashProject.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarwashProject.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231015073041_addcars")]
    partial class addcars
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarwashProject.Domain.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Manifacturing")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Manifacturing = 0,
                            Name = "Pride"
                        },
                        new
                        {
                            Id = 2,
                            Manifacturing = 0,
                            Name = "Peugeot"
                        },
                        new
                        {
                            Id = 3,
                            Manifacturing = 0,
                            Name = "PeugeotPars"
                        },
                        new
                        {
                            Id = 4,
                            Manifacturing = 0,
                            Name = "Samand"
                        },
                        new
                        {
                            Id = 5,
                            Manifacturing = 0,
                            Name = "Tiba"
                        },
                        new
                        {
                            Id = 6,
                            Manifacturing = 0,
                            Name = "Runu"
                        },
                        new
                        {
                            Id = 7,
                            Manifacturing = 0,
                            Name = "Denu"
                        },
                        new
                        {
                            Id = 8,
                            Manifacturing = 0,
                            Name = "Quick"
                        },
                        new
                        {
                            Id = 9,
                            Manifacturing = 0,
                            Name = "Vanet"
                        },
                        new
                        {
                            Id = 10,
                            Manifacturing = 0,
                            Name = "206"
                        },
                        new
                        {
                            Id = 11,
                            Manifacturing = 0,
                            Name = "207"
                        },
                        new
                        {
                            Id = 12,
                            Manifacturing = 0,
                            Name = "H30Cras"
                        },
                        new
                        {
                            Id = 13,
                            Manifacturing = 0,
                            Name = "Arrizo"
                        },
                        new
                        {
                            Id = 14,
                            Manifacturing = 0,
                            Name = "Santafa"
                        },
                        new
                        {
                            Id = 15,
                            Manifacturing = 0,
                            Name = "MVM"
                        });
                });

            modelBuilder.Entity("CarwashProject.Domain.Entities.Khadamat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Khadamats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Roshoei",
                            Price = 60000m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Broom",
                            Price = 40000m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Wax",
                            Price = 50000m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Enginewash",
                            Price = 80000m
                        });
                });

            modelBuilder.Entity("CarwashProject.Domain.Entities.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("CarwashProject.Domain.Entities.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Workers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            Bonus = 0m,
                            FirstName = "ali",
                            LastName = "ahmadi",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 2,
                            Age = 21,
                            Bonus = 0m,
                            FirstName = "majid",
                            LastName = "majidi",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 3,
                            Age = 22,
                            Bonus = 0m,
                            FirstName = "farhad",
                            LastName = "farhadi",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 4,
                            Age = 23,
                            Bonus = 0m,
                            FirstName = "soheil",
                            LastName = "soheily",
                            Salary = 0m
                        });
                });

            modelBuilder.Entity("CarwashProject.Domain.Entities.WorkerInKhadamat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KhadamatId")
                        .HasColumnType("int");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhadamatId");

                    b.HasIndex("WorkerId");

                    b.ToTable("WorkerInKhadamat");
                });

            modelBuilder.Entity("CarwashProject.Domain.Entities.WorkerInKhadamat", b =>
                {
                    b.HasOne("CarwashProject.Domain.Entities.Khadamat", "Khadamat")
                        .WithMany("WorkerInKhadamats")
                        .HasForeignKey("KhadamatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarwashProject.Domain.Entities.Worker", "Worker")
                        .WithMany("WorkerInKhadamats")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khadamat");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("CarwashProject.Domain.Entities.Khadamat", b =>
                {
                    b.Navigation("WorkerInKhadamats");
                });

            modelBuilder.Entity("CarwashProject.Domain.Entities.Worker", b =>
                {
                    b.Navigation("WorkerInKhadamats");
                });
#pragma warning restore 612, 618
        }
    }
}
